/* eslint-disable @typescript-eslint/no-explicit-any */
import { createRequire } from "node:module";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import {
  listSnapshots,
  loadSnapshot,
  openInEditor,
  saveSnapshot,
  type OpenBody,
  type SaveBody,
  type StarlingServerOptions,
} from "./server";

/**
 * `withStarling()` — the one-line, dev-only Next config wrapper that registers
 * Starling's source-stamping loader. Wrap your existing config:
 *
 *   import { withStarling } from "@starling/dev/next/config";
 *   const nextConfig = { ...your config... };
 *   export default withStarling(nextConfig);
 *
 * Properties:
 * - **No-op in production** (and when `enabled: false`): returns your config
 *   untouched, so nothing is registered in prod builds.
 * - **Auto-mounts the endpoints:** on dev startup it creates the App Router route
 *   file (`<app>/api/starling/[action]/route.ts`) that serves save/list/load, so
 *   you only touch `next.config`. Idempotent; opt out with `autoRoute: false`.
 *   (Next has no config seam to register a route at runtime — unlike Vite — so
 *   the file must exist on disk; this just writes it for you.)
 * - **Composes:** spreads your config and chains any existing `webpack(...)` fn
 *   last, so your customizations win.
 * - Registers the source-stamping loader on the **webpack** dev rule.
 *
 * Caveat (PRD §12): Turbopack — Next's default dev engine — does not reliably run
 * a Babel-AST loader (its loader model is for simple text rewriting; registering
 * one re-processes the loader output and doubles the module extension). So this
 * wrapper does NOT add a Turbopack rule. On the default Turbopack dev server
 * Starling runs WITHOUT Tier-1 source stamping and relies on its selector
 * locators — fully functional either way (source attributes are an enrichment,
 * and are pure DOM, so Rewind/anchoring are unaffected). For guaranteed source
 * stamping, run the host with `next dev --webpack`.
 */
export interface WithStarlingOptions {
  /** Project root used to make stamped paths repo-relative. Default: cwd. */
  root?: string;
  /** Force enable/disable. Default: enabled only outside production. */
  enabled?: boolean;
  /**
   * Auto-create the App Router route file that serves save/list/load on dev
   * startup (Next has no config seam to mount routes — the file must exist on
   * disk). Idempotent: skipped when the file already exists. Default: true.
   * Set false to manage the route file yourself.
   */
  autoRoute?: boolean;
  /**
   * Where the app directory lives, relative to `root`. Default: auto-detect —
   * `src/app` if present, else `app`. Set explicitly to override.
   */
  appDir?: "src/app" | "app";
}

/**
 * Write `<appDir>/api/starling/[action]/route.ts` if absent, re-exporting the
 * route factory. The host never hand-writes (or copy-pastes) the handler, so the
 * email/author fallback can never drift out of a stale copy. Best-effort: any
 * failure (read-only FS, odd layout) is swallowed — the host can still add the
 * file manually. Returns the path written, or null when skipped.
 */
function scaffoldRoute(root: string, appDir?: "src/app" | "app"): string | null {
  try {
    const dir =
      appDir ?? (existsSync(join(root, "src/app")) ? "src/app" : "app");
    // Only scaffold into an app that actually uses the App Router.
    if (!existsSync(join(root, dir))) return null;

    const file = join(root, dir, "api", "starling", "[action]", "route.ts");
    if (existsSync(file)) return null;

    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(
      file,
      `// Auto-generated by withStarling() — serves Starling's save/list/load.\n` +
        `// Safe to delete; it'll be recreated on next dev start (or remove the\n` +
        `// <Starling/> mount + withStarling wrapper to uninstall entirely).\n` +
        `import { createStarlingRoute } from "@starling/dev/next/config";\n\n` +
        `export const { GET, POST } = createStarlingRoute();\n`,
      "utf8",
    );
    return file;
  } catch {
    return null;
  }
}

export function withStarling<T extends Record<string, any>>(
  nextConfig: T = {} as T,
  opts: WithStarlingOptions = {},
): T {
  const enabled = opts.enabled ?? process.env.NODE_ENV !== "production";
  if (!enabled) return nextConfig;

  const root = opts.root ?? process.cwd();
  // Mount the dev-server endpoints by ensuring the route file exists. This is the
  // step that brings save/list/load (and author stamping) online.
  if (opts.autoRoute !== false) {
    const written = scaffoldRoute(root, opts.appDir);
    if (written) {
      console.log(`[starling] created ${written}`);
    }
  }

  // The built CJS loader sits next to this module in dist/plugin/. Resolve it
  // defensively: source-stamping is an optional enrichment, so a resolution
  // failure (e.g. running from un-built source) must NOT take down the host's
  // next.config — the endpoints (scaffolded above) and selector locators still
  // work. Returns the config with the loader rule only when resolution succeeds.
  let loaderPath: string | null = null;
  try {
    loaderPath = createRequire(import.meta.url).resolve("./loader.cjs");
  } catch {
    loaderPath = null;
  }

  const userWebpack = (nextConfig as any).webpack as
    | ((config: any, ctx: any) => any)
    | undefined;
  const rule = loaderPath ? { loader: loaderPath, options: { root } } : null;

  return {
    ...nextConfig,
    // Next 16 errors on a `webpack` config with no `turbopack` config (Turbopack
    // is the default engine). An empty turbopack config silences that check while
    // we intentionally register only the webpack rule (see caveat above).
    turbopack: { ...(nextConfig as any).turbopack },
    webpack(config: any, ctx: any) {
      if (ctx?.dev && rule) {
        config.module.rules.push({
          test: /\.[jt]sx$/,
          exclude: /node_modules/,
          use: [rule],
        });
      }
      return typeof userWebpack === "function" ? userWebpack(config, ctx) : config;
    },
  } as T;
}

export default withStarling;

/**
 * Next App Router route handlers for Starling's SAVE/LIST/LOAD endpoints. Next's
 * dev server has no `next.config` middleware seam (unlike Vite), so the host drops
 * ONE catch-all route file in that re-exports these. Authorship is stamped here,
 * server-side, from `git config user.name`.
 *
 *   // app/api/starling/[action]/route.ts
 *   import { createStarlingRoute } from "@starling/dev/next/config";
 *   export const { GET, POST } = createStarlingRoute();
 *
 * The `[action]` segment ("save" | "list" | "load") is read from the URL, so a
 * single file serves all three. Match the component's endpoints to this path
 * (the defaults already do):
 *
 *   <Starling
 *     saveEndpoint="/api/starling/save"
 *     listEndpoint="/api/starling/list"
 *     loadEndpoint="/api/starling/load"
 *   />
 */
export function createStarlingRoute(options: StarlingServerOptions = {}) {
  const action = (req: Request) => {
    const segs = new URL(req.url).pathname.split("/").filter(Boolean);
    return segs[segs.length - 1] ?? "";
  };
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { "content-type": "application/json" },
    });

  async function POST(req: Request): Promise<Response> {
    const which = action(req);
    if (which === "open") {
      try {
        const body = (await req.json()) as OpenBody;
        return json(await openInEditor(body, options));
      } catch {
        return json({ ok: false, error: "open failed" }, 500);
      }
    }
    if (which !== "save") return json({ error: "not found" }, 404);
    try {
      // `appId` rides in the body (the browser sets it from the <Starling/> prop).
      const body = (await req.json()) as SaveBody;
      return json(await saveSnapshot(body, options));
    } catch {
      return json({ error: "save failed" }, 500);
    }
  }

  async function GET(req: Request): Promise<Response> {
    const url = new URL(req.url);
    const which = action(req);
    // list/load carry the app scope as `?app=<id>`.
    const appId = url.searchParams.get("app") ?? "";
    if (which === "list") {
      return json({ snapshots: await listSnapshots(appId, options) });
    }
    if (which === "load") {
      const id = url.searchParams.get("file") ?? "";
      const session = await loadSnapshot(id, appId, options);
      return session == null
        ? json({ error: "not found" }, 404)
        : new Response(session, {
            status: 200,
            headers: { "content-type": "application/json" },
          });
    }
    return json({ error: "not found" }, 404);
  }

  return { GET, POST };
}
